#!/usr/bin/env python3
"""R0.22 audit of the analytic-radius loss in the cone lattice norm.

The R0.21 mode norm

    N_delta(v) = |v| + delta^(-1) |(1,1,1) . v|

removes every explicit negative power of delta from a single cone-frequency
interaction.  This audit asks the next question: how many powers of the
charge-offset label remain in the bilinear operator?

In cube coordinates m in Z^3 with equal coordinate parity, let
r(m) = |m|_infinity.  The script verifies the general two-label upper bound
behind an analytic radius loss of order two.  It also constructs an exact
one-parameter family of two divergence-free modes for which

    r(m_A + m_B) = r(m_A) + r(m_B)

and the ordered interaction grows as (27/2) N^2.  The symmetrized quadratic
interaction grows as 27 N^2.  Therefore a radius-loss exponent smaller than
two is impossible for this full-space norm scale.

This is a method obstruction, not a Navier--Stokes singularity or regularity
result.  It does not rule out sharper estimates on the invariant coefficient
subspace generated by the selected initial data, or cancellations after full
tree aggregation.
"""

from __future__ import annotations

import argparse
from fractions import Fraction
import json
import math
from pathlib import Path
import platform
import subprocess
import sys
import time
from typing import Iterable

import numpy as np


Rational = Fraction
IntegerVector = tuple[int, int, int]
RationalVector = tuple[Rational, Rational, Rational]
DEFAULT_PARAMETERS = (2, 3, 5, 8, 13, 21, 34, 55, 89)
DIRECTION = np.array([1.0, 1.0, 1.0])


def progress(enabled: bool, started: float, message: str) -> None:
    if enabled:
        elapsed = time.perf_counter() - started
        print(f"[R0.22 +{elapsed:7.2f}s] {message}", file=sys.stderr, flush=True)


def git_source_state() -> dict[str, object]:
    commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    dirty = bool(
        subprocess.check_output(["git", "status", "--porcelain"], text=True).strip()
    )
    return {"commit": commit, "dirty": dirty}


def add(left: IntegerVector, right: IntegerVector) -> IntegerVector:
    return tuple(left[index] + right[index] for index in range(3))  # type: ignore[return-value]


def radius(label: IntegerVector) -> int:
    return max(abs(component) for component in label)


def in_cone_lattice(label: IntegerVector) -> bool:
    return (label[0] - label[1]) % 2 == 0 and (label[0] - label[2]) % 2 == 0


def charge(label: IntegerVector) -> Rational:
    return Rational(3 * label[0] - label[2], 12)


def offset(label: IntegerVector) -> RationalVector:
    _, second, third = label
    return (
        Rational(third, 3),
        Rational(3 * second - third, 6),
        Rational(-(3 * second + third), 6),
    )


def dot(left: RationalVector, right: RationalVector) -> Rational:
    return sum(
        (left[index] * right[index] for index in range(3)),
        start=Rational(0),
    )


def cross(left: RationalVector, right: RationalVector) -> RationalVector:
    return (
        left[1] * right[2] - left[2] * right[1],
        left[2] * right[0] - left[0] * right[2],
        left[0] * right[1] - left[1] * right[0],
    )


def squared_norm(value: RationalVector) -> Rational:
    return dot(value, value)


def parameter_labels(parameter: int) -> tuple[IntegerVector, IntegerVector, IntegerVector]:
    mode_a = (parameter, -3 * parameter, 3 * parameter - 2)
    mode_b = (-parameter + 1, -3 * parameter + 1, -3 * parameter + 1)
    return mode_a, mode_b, add(mode_a, mode_b)


def rational_vector_record(value: RationalVector) -> list[str]:
    return [str(component) for component in value]


def exact_record(parameter: int) -> dict[str, object]:
    mode_a, mode_b, output = parameter_labels(parameter)
    beta_a = offset(mode_a)
    beta_b = offset(mode_b)
    beta_output = offset(output)
    diagonal: RationalVector = (Rational(1), Rational(1), Rational(1))
    cross_a = cross(diagonal, beta_a)
    cross_b = cross(diagonal, beta_b)
    determinant = dot(beta_b, cross_a)

    return {
        "parameter": parameter,
        "labels": {
            "a": list(mode_a),
            "b": list(mode_b),
            "output": list(output),
        },
        "charges": {
            "a": str(charge(mode_a)),
            "b": str(charge(mode_b)),
            "output": str(charge(output)),
        },
        "offsets": {
            "a": rational_vector_record(beta_a),
            "b": rational_vector_record(beta_b),
            "output": rational_vector_record(beta_output),
        },
        "radii": {
            "a": radius(mode_a),
            "b": radius(mode_b),
            "output": radius(output),
            "exactlyAdditive": radius(output) == radius(mode_a) + radius(mode_b),
        },
        "latticeMembership": {
            "a": in_cone_lattice(mode_a),
            "b": in_cone_lattice(mode_b),
            "output": in_cone_lattice(output),
        },
        "polarizationNumerators": {
            "dCrossBetaA": rational_vector_record(cross_a),
            "dCrossBetaB": rational_vector_record(cross_b),
            "squaredNormA": str(squared_norm(cross_a)),
            "squaredNormB": str(squared_norm(cross_b)),
        },
        "mixedDeterminant": str(determinant),
        "expectedMixedDeterminant": str(-(3 * parameter - 1) ** 2),
        "exactIdentities": {
            "offsetsTransverse": (
                sum(beta_a, start=Rational(0)) == 0
                and sum(beta_b, start=Rational(0)) == 0
                and sum(beta_output, start=Rational(0)) == 0
            ),
            "inputPolarizationsHaveZeroLongitudinalSeminorm": (
                dot(beta_a, cross_a) == 0
                and dot(diagonal, cross_a) == 0
                and dot(beta_b, cross_b) == 0
                and dot(diagonal, cross_b) == 0
            ),
        },
    }


def to_float(value: RationalVector) -> np.ndarray:
    return np.array([float(component) for component in value], dtype=np.float64)


def leray_projection(frequency_direction: np.ndarray, value: np.ndarray) -> np.ndarray:
    return value - frequency_direction * (
        np.dot(frequency_direction, value) / np.dot(frequency_direction, frequency_direction)
    )


def numerical_record(parameter: int) -> dict[str, object]:
    mode_a, mode_b, output = parameter_labels(parameter)
    beta_a = to_float(offset(mode_a))
    beta_b = to_float(offset(mode_b))
    beta_output = to_float(offset(output))
    q_output = float(charge(output))
    cross_a = np.cross(DIRECTION, beta_a)
    cross_b = np.cross(DIRECTION, beta_b)
    polarization_a = cross_a / np.linalg.norm(cross_a)
    polarization_b = cross_b / np.linalg.norm(cross_b)

    # delta = 4^(-parameter) makes delta |beta| tend rapidly to zero while
    # remaining an admissible shell sequence.
    delta = 4.0 ** (-parameter)
    output_direction = q_output * DIRECTION + delta * beta_output
    scalar_ab = float(np.dot(beta_b, polarization_a))
    scalar_ba = float(np.dot(beta_a, polarization_b))

    ordered_raw = scalar_ab * polarization_b
    symmetrized_raw = ordered_raw + scalar_ba * polarization_a
    ordered = leray_projection(output_direction, ordered_raw)
    symmetrized = leray_projection(output_direction, symmetrized_raw)

    def mode_norm(value: np.ndarray) -> float:
        # The projected output is divergence free, so the stable charge-offset
        # identity avoids subtracting nearly equal delta-scale numbers.
        longitudinal = abs(float(np.dot(beta_output, value))) / abs(q_output)
        return float(np.linalg.norm(value)) + longitudinal

    ordered_norm = mode_norm(ordered)
    symmetrized_norm = mode_norm(symmetrized)
    heat_a = 3.0 * float(charge(mode_a)) ** 2 + delta**2 * float(np.dot(beta_a, beta_a))
    heat_b = 3.0 * float(charge(mode_b)) ** 2 + delta**2 * float(np.dot(beta_b, beta_b))
    heat_output = 3.0 * q_output**2 + delta**2 * float(np.dot(beta_output, beta_output))

    return {
        "parameter": parameter,
        "delta": delta,
        "orderedModeNorm": ordered_norm,
        "orderedModeNormOverParameterSquared": ordered_norm / parameter**2,
        "symmetrizedModeNorm": symmetrized_norm,
        "symmetrizedModeNormOverParameterSquared": symmetrized_norm / parameter**2,
        "inputModeNorms": [1.0, 1.0],
        "dimensionlessHeatRates": {
            "a": heat_a,
            "b": heat_b,
            "output": heat_output,
        },
    }


def analytic_upper_constant(radius_gap: float) -> dict[str, float]:
    first_order = 1.0 / (math.e * radius_gap)
    second_order = 24.0 / (math.e**2 * radius_gap**2)
    return {
        "radiusGap": radius_gap,
        "firstOrderPart": first_order,
        "secondOrderPart": second_order,
        "totalUpperBound": first_order + second_order,
    }


def audit(parameters: Iterable[int], show_progress: bool = False) -> dict[str, object]:
    started = time.perf_counter()
    parameter_list = list(parameters)
    exact = [exact_record(parameter) for parameter in parameter_list]
    progress(show_progress, started, "verified the exact lattice and determinant identities")
    numerical = [numerical_record(parameter) for parameter in parameter_list]
    progress(show_progress, started, "evaluated the ordered and symmetrized sharpness family")

    return {
        "scope": {
            "result": "sharp second-order analytic-radius loss for the full R0.21 mode norm",
            "notClaimed": [
                "failure of the selected Taylor coefficient subspace",
                "failure of all possible analytic or tree-level norms",
                "a Navier--Stokes regularity or singularity result",
            ],
        },
        "coneLattice": {
            "definition": "m in Z^3 with m_1, m_2, m_3 of equal parity",
            "radius": "r(m) = max(|m_1|, |m_2|, |m_3|)",
            "charge": "q(m) = (3 m_1 - m_3) / 12",
            "offsetSquaredNorm": "|beta(m)|^2 = (m_2^2 + m_3^2) / 2",
            "nonzeroChargeGap": "|q| >= 1/6",
        },
        "upperBound": {
            "modeNorm": "N_delta(v) = |v| + delta^-1 |(1,1,1).v|",
            "orderedModeEstimate": (
                "N_delta(B_m(u_a,v_b)) <= (1 + 6 r(m)) r(b) "
                "N_delta(u_a) N_delta(v_b)"
            ),
            "analyticScaleEstimate": (
                "||B(u,v)||_(rho-eta) <= [1/(e eta) + 24/(e^2 eta^2)] "
                "||u||_rho ||v||_rho"
            ),
            "sampleConstants": [
                analytic_upper_constant(gap) for gap in (0.5, 0.25, 0.125, 0.0625)
            ],
        },
        "sharpnessFamily": {
            "labels": {
                "a": "(N, -3N, 3N-2)",
                "b": "(-N+1, -3N+1, -3N+1)",
                "output": "(1, -6N+1, -1)",
            },
            "charges": {"a": "1/6", "b": "1/6", "output": "1/3"},
            "radiusIdentity": "r(output) = r(a) + r(b) = 6N - 1",
            "polarizations": "w_j = ((1,1,1) cross beta_j) / |(1,1,1) cross beta_j|",
            "mixedDeterminant": "beta_b . ((1,1,1) cross beta_a) = -(3N-1)^2",
            "orderedAsymptotic": "N_delta(B(w_a,w_b)) / N^2 -> 27/2",
            "symmetrizedAsymptotic": "N_delta(B(w_a,w_b)+B(w_b,w_a)) / N^2 -> 27",
            "radiusLossConclusion": "no analytic-scale bound with eta exponent p < 2",
            "heatConclusion": (
                "for delta_N=4^-N, transverse heat rates vanish while charge heat rates stay bounded; "
                "the dimensionless heat multiplier does not supply an N^2 gain on this family"
            ),
        },
        "exactChecks": exact,
        "numericalLimits": numerical,
        "expectedLimits": {
            "orderedModeNormOverParameterSquared": 13.5,
            "symmetrizedModeNormOverParameterSquared": 27.0,
            "inputHeatRate": 1.0 / 12.0,
            "outputHeatRate": 1.0 / 3.0,
        },
        "environment": {
            "python": platform.python_version(),
            "numpy": np.__version__,
            "platform": platform.platform(),
        },
        "git": git_source_state(),
        "wallSeconds": time.perf_counter() - started,
    }


def validate(result: dict[str, object]) -> None:
    for record in result["exactChecks"]:
        assert all(record["latticeMembership"].values())
        assert record["radii"]["exactlyAdditive"] is True
        assert record["charges"] == {"a": "1/6", "b": "1/6", "output": "1/3"}
        assert record["mixedDeterminant"] == record["expectedMixedDeterminant"]
        assert record["exactIdentities"]["offsetsTransverse"] is True
        assert record["exactIdentities"]["inputPolarizationsHaveZeroLongitudinalSeminorm"] is True

    final = result["numericalLimits"][-1]
    assert abs(final["orderedModeNormOverParameterSquared"] - 13.5) < 0.2
    assert abs(final["symmetrizedModeNormOverParameterSquared"] - 27.0) < 0.4
    assert abs(final["dimensionlessHeatRates"]["a"] - 1.0 / 12.0) < 1.0e-12
    assert abs(final["dimensionlessHeatRates"]["b"] - 1.0 / 12.0) < 1.0e-12
    assert abs(final["dimensionlessHeatRates"]["output"] - 1.0 / 3.0) < 1.0e-12


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--parameters", nargs="+", type=int, default=list(DEFAULT_PARAMETERS))
    parser.add_argument("--output", type=Path)
    parser.add_argument("--pretty", action="store_true")
    parser.add_argument("--progress", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    if not arguments.parameters or min(arguments.parameters) < 2:
        parser.error("all sharpness parameters must be integers at least 2")
    result = audit(arguments.parameters, arguments.progress)
    if arguments.check:
        validate(result)
    serialized = json.dumps(
        result,
        ensure_ascii=False,
        indent=2 if arguments.pretty else None,
        sort_keys=True,
    )
    if arguments.output:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(serialized + "\n")
    print(serialized)


if __name__ == "__main__":
    main()
