#!/usr/bin/env python3
"""R0.23 exact cone-limit audit of the first sharp-label encounter.

R0.22 constructed a full-space polarization family with a sharp quadratic
analytic-radius loss.  This script asks whether the Taylor coefficients
generated by the optimized R0.20 eight-mode datum actually meet that family.

For a cone mode K_delta(m) = delta^(-1) q(m) d + beta(m), write a
divergence-free coefficient as the limiting pair

    w = lim u_delta,       ell = lim delta^(-1) d . u_delta.

The ordered Navier--Stokes bilinear map closes exactly on (w, ell).  At the
rational R0.20 root center, the normalized catalyst-to-pump weight t satisfies

    t^2 = x (1 + p^2/12) / (4 (1 + q^2/3)).

Consequently every pure nonlinear Taylor coefficient belongs to the real
quadratic field Q(t).  The script propagates the complete coefficient fields
through time order ten with Fraction arithmetic, then audits the N=2 labels
from the R0.22 sharp family.  It proves exact nonvanishing statements at this
one rational root center.  It does not prove uniform control of the R0.20 root
box, an all-N asymptotic estimate, or a Navier--Stokes regularity theorem.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import platform
import subprocess
import sys
import time
from typing import Iterable

try:
    import gmpy2

    Rational = gmpy2.mpq
    RATIONAL_BACKEND = f"gmpy2.mpq (GMP {gmpy2.mp_version()})"
except ImportError:
    from fractions import Fraction

    Rational = Fraction
    RATIONAL_BACKEND = "fractions.Fraction"

Label = tuple[int, int, int]
RationalVector = tuple[Rational, Rational, Rational]
Quadratic = tuple[Rational, Rational]
QuadraticVector = tuple[Quadratic, Quadratic, Quadratic]
ConeCoefficient = tuple[Quadratic, Quadratic, Quadratic, Quadratic]
Field = dict[Label, ConeCoefficient]

ZERO_R = Rational(0)
ZERO_Q: Quadratic = (ZERO_R, ZERO_R)
ZERO_COEFFICIENT: ConeCoefficient = (ZERO_Q, ZERO_Q, ZERO_Q, ZERO_Q)
DIRECTION: RationalVector = (Rational(1), Rational(1), Rational(1))
ROOT_CERTIFICATE = Path("research/certificates/r020/interior-root-certificates.json")
MAXIMUM_ORDER = 10
SHARPNESS_PARAMETER = 2

# The eight cube vertices are in the same order as signed_frequencies() in
# fifth_order_tree_audit.py.  Negative Fourier coefficients copy the real
# polarization of their positive partners.
INITIAL_LABELS: tuple[Label, ...] = (
    (1, 1, 1),
    (1, -1, 1),
    (1, 1, -1),
    (1, -1, -1),
    (-1, -1, -1),
    (-1, 1, -1),
    (-1, -1, 1),
    (-1, 1, 1),
)
BASE_TRANSVERSE: tuple[RationalVector, ...] = (
    (Rational(-1), Rational(-1), Rational(2)),
    (Rational(1), Rational(-2), Rational(1)),
    (Rational(1), Rational(-2), Rational(1)),
    (Rational(-1), Rational(-1), Rational(2)),
)
CHART_TRANSVERSE: tuple[RationalVector, ...] = (
    (Rational(1, 2), Rational(-1, 2), ZERO_R),
    (Rational(1, 2), ZERO_R, Rational(-1, 2)),
    (Rational(1), ZERO_R, Rational(-1)),
    (Rational(1), Rational(-1), ZERO_R),
)
CHART_SECOND_ORDER: tuple[RationalVector, ...] = (
    (Rational(4), Rational(-4), ZERO_R),
    (Rational(4), ZERO_R, Rational(-4)),
    (Rational(2), ZERO_R, Rational(-2)),
    (Rational(2), Rational(-2), ZERO_R),
)
BASE_LONGITUDINAL = (Rational(12), Rational(-12), Rational(6), Rational(-6))


def progress(enabled: bool, started: float, message: str) -> None:
    if enabled:
        elapsed = time.perf_counter() - started
        print(f"[R0.23 +{elapsed:7.2f}s] {message}", file=sys.stderr, flush=True)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def git_source_state() -> dict[str, object]:
    commit = subprocess.check_output(["git", "rev-parse", "HEAD"], text=True).strip()
    dirty = bool(
        subprocess.check_output(["git", "status", "--porcelain"], text=True).strip()
    )
    return {"commit": commit, "dirty": dirty}


def q_add(left: Quadratic, right: Quadratic) -> Quadratic:
    return left[0] + right[0], left[1] + right[1]


def q_neg(value: Quadratic) -> Quadratic:
    return -value[0], -value[1]


def q_scale(value: Rational | int, element: Quadratic) -> Quadratic:
    factor = Rational(value)
    return factor * element[0], factor * element[1]


def q_multiply(left: Quadratic, right: Quadratic, radicand: Rational) -> Quadratic:
    return (
        left[0] * right[0] + radicand * left[1] * right[1],
        left[0] * right[1] + left[1] * right[0],
    )


def q_divide(left: Quadratic, right: Quadratic, radicand: Rational) -> Quadratic:
    denominator = right[0] * right[0] - radicand * right[1] * right[1]
    if denominator == 0:
        raise ZeroDivisionError("division by zero in the quadratic field")
    conjugate = (right[0], -right[1])
    return q_scale(Rational(1, 1) / denominator, q_multiply(left, conjugate, radicand))


def q_is_zero(value: Quadratic) -> bool:
    return value == ZERO_Q


def q_float(value: Quadratic, radicand: Rational) -> float:
    return float(value[0]) + float(value[1]) * math.sqrt(float(radicand))


def rational_is_square(value: Rational) -> bool:
    numerator_root = math.isqrt(value.numerator)
    denominator_root = math.isqrt(value.denominator)
    return (
        numerator_root * numerator_root == value.numerator
        and denominator_root * denominator_root == value.denominator
    )


def coefficient_add(left: ConeCoefficient, right: ConeCoefficient) -> ConeCoefficient:
    return tuple(q_add(left[index], right[index]) for index in range(4))  # type: ignore[return-value]


def coefficient_scale(
    value: Rational | int,
    coefficient: ConeCoefficient,
) -> ConeCoefficient:
    return tuple(q_scale(value, component) for component in coefficient)  # type: ignore[return-value]


def coefficient_is_zero(coefficient: ConeCoefficient) -> bool:
    return all(q_is_zero(component) for component in coefficient)


def field_add(field: Field, label: Label, coefficient: ConeCoefficient) -> None:
    if coefficient_is_zero(coefficient):
        return
    updated = coefficient_add(field.get(label, ZERO_COEFFICIENT), coefficient)
    if coefficient_is_zero(updated):
        field.pop(label, None)
    else:
        field[label] = updated


def label_add(left: Label, right: Label) -> Label:
    return tuple(left[index] + right[index] for index in range(3))  # type: ignore[return-value]


def radius(label: Label) -> int:
    return max(abs(component) for component in label)


def charge(label: Label) -> Rational:
    return Rational(3 * label[0] - label[2], 12)


def offset(label: Label) -> RationalVector:
    _, second, third = label
    return (
        Rational(third, 3),
        Rational(3 * second - third, 6),
        Rational(-(3 * second + third), 6),
    )


def rational_dot(left: RationalVector, right: RationalVector) -> Rational:
    return sum((left[index] * right[index] for index in range(3)), start=ZERO_R)


def rational_cross(left: RationalVector, right: RationalVector) -> RationalVector:
    return (
        left[1] * right[2] - left[2] * right[1],
        left[2] * right[0] - left[0] * right[2],
        left[0] * right[1] - left[1] * right[0],
    )


def rational_dot_quadratic(
    left: RationalVector,
    right: Iterable[Quadratic],
) -> Quadratic:
    result = ZERO_Q
    for scalar, component in zip(left, right, strict=True):
        result = q_add(result, q_scale(scalar, component))
    return result


def quadratic_dot(
    left: Iterable[Quadratic],
    right: Iterable[Quadratic],
    radicand: Rational,
) -> Quadratic:
    result = ZERO_Q
    for left_component, right_component in zip(left, right, strict=True):
        result = q_add(
            result,
            q_multiply(left_component, right_component, radicand),
        )
    return result


def constraint(label: Label, coefficient: ConeCoefficient) -> Quadratic:
    return q_add(
        q_scale(charge(label), coefficient[3]),
        rational_dot_quadratic(offset(label), coefficient[:3]),
    )


def cone_bilinear(
    left_label: Label,
    left: ConeCoefficient,
    right_label: Label,
    right: ConeCoefficient,
    radicand: Rational,
) -> tuple[Label, ConeCoefficient]:
    output_label = label_add(left_label, right_label)
    scalar = q_add(
        rational_dot_quadratic(offset(right_label), left[:3]),
        q_scale(charge(right_label), left[3]),
    )
    if q_is_zero(scalar):
        return output_label, ZERO_COEFFICIENT

    output_charge = charge(output_label)
    output_offset = offset(output_label)
    if output_charge != 0:
        transverse = tuple(
            q_multiply(scalar, right[index], radicand) for index in range(3)
        )
        longitudinal = q_scale(
            -Rational(1, 1) / output_charge,
            rational_dot_quadratic(output_offset, transverse),
        )
        output: ConeCoefficient = transverse + (longitudinal,)  # type: ignore[assignment]
    elif output_offset != (ZERO_R, ZERO_R, ZERO_R):
        offset_squared = rational_dot(output_offset, output_offset)
        offset_component = rational_dot_quadratic(output_offset, right[:3])
        projected = tuple(
            q_add(
                right[index],
                q_scale(-output_offset[index] / offset_squared, offset_component),
            )
            for index in range(3)
        )
        transverse = tuple(
            q_multiply(scalar, projected[index], radicand) for index in range(3)
        )
        longitudinal = q_multiply(scalar, right[3], radicand)
        output = transverse + (longitudinal,)  # type: ignore[assignment]
    else:
        # The zero Fourier mode vanishes because right_label = -left_label and
        # the left coefficient is divergence-free.
        return output_label, ZERO_COEFFICIENT

    if constraint(output_label, output) != ZERO_Q:
        raise AssertionError(f"output constraint failed at label {output_label}")
    return output_label, output


def load_root_center() -> tuple[dict[str, Rational], Rational, str]:
    payload = json.loads(ROOT_CERTIFICATE.read_text())
    root = payload["roots"][0]
    center = {
        variable: Rational(root["polishedRoot"][variable])
        for variable in ("p", "q", "x")
    }
    radius_value = Rational(root["stationarySystemCertificate"]["radius"])
    return center, radius_value, sha256(ROOT_CERTIFICATE)


def initial_field(center: dict[str, Rational], radicand: Rational) -> Field:
    del radicand  # The radical basis element itself is represented by (0, 1).
    p_value, q_value = center["p"], center["q"]
    positive: list[ConeCoefficient] = []
    for index in range(4):
        chart_value = (p_value, -p_value, q_value, -q_value)[index]
        transverse_rational = tuple(
            BASE_TRANSVERSE[index][axis]
            + chart_value * CHART_TRANSVERSE[index][axis]
            for axis in range(3)
        )
        weight = (Rational(1), ZERO_R) if index < 2 else (ZERO_R, Rational(1))
        coefficient: ConeCoefficient = tuple(
            q_scale(component, weight) for component in transverse_rational
        ) + (q_scale(BASE_LONGITUDINAL[index], weight),)  # type: ignore[assignment]
        positive.append(coefficient)

    field: Field = {}
    for label, coefficient in zip(INITIAL_LABELS, positive + positive, strict=True):
        if constraint(label, coefficient) != ZERO_Q:
            raise AssertionError(f"initial constraint failed at label {label}")
        field_add(field, label, coefficient)
    return field


def pure_nonlinear_taylor(
    initial: Field,
    radicand: Rational,
    maximum_order: int,
    show_progress: bool,
    started: float,
) -> tuple[list[Field], list[dict[str, int]]]:
    coefficients = [initial]
    summaries = [
        {
            "timeOrder": 0,
            "leafCount": 1,
            "supportSize": len(initial),
            "orderedInteractions": 0,
        }
    ]
    for next_order in range(1, maximum_order + 1):
        output: Field = {}
        interaction_count = 0
        for left_order in range(next_order):
            right_order = next_order - 1 - left_order
            for left_label, left in coefficients[left_order].items():
                for right_label, right in coefficients[right_order].items():
                    interaction_count += 1
                    output_label, value = cone_bilinear(
                        left_label,
                        left,
                        right_label,
                        right,
                        radicand,
                    )
                    field_add(
                        output,
                        output_label,
                        coefficient_scale(Rational(-1, next_order), value),
                    )
        for label, value in output.items():
            if constraint(label, value) != ZERO_Q:
                raise AssertionError(f"aggregated constraint failed at label {label}")
        coefficients.append(output)
        summaries.append(
            {
                "timeOrder": next_order,
                "leafCount": next_order + 1,
                "supportSize": len(output),
                "orderedInteractions": interaction_count,
            }
        )
        progress(
            show_progress,
            started,
            f"order {next_order:2d}: support {len(output):4d}, "
            f"ordered interactions {interaction_count:7d}",
        )
    return coefficients, summaries


def sharp_labels(parameter: int) -> tuple[Label, Label, Label]:
    left = (parameter, -3 * parameter, 3 * parameter - 2)
    right = (-parameter + 1, -3 * parameter + 1, -3 * parameter + 1)
    return left, right, label_add(left, right)


def q_record(value: Quadratic, radicand: Rational) -> dict[str, object]:
    return {
        "basis": [str(value[0]), str(value[1])],
        "expression": f"({value[0]}) + ({value[1]}) t",
        "decimal": q_float(value, radicand),
        "isExactlyZero": q_is_zero(value),
    }


def coefficient_mode_norm(coefficient: ConeCoefficient, radicand: Rational) -> float:
    transverse = [q_float(component, radicand) for component in coefficient[:3]]
    longitudinal = q_float(coefficient[3], radicand)
    return math.sqrt(sum(component * component for component in transverse)) + abs(
        longitudinal
    )


def coefficient_record(
    label: Label,
    coefficient: ConeCoefficient,
    radicand: Rational,
) -> dict[str, object]:
    sharp_direction = rational_cross(DIRECTION, offset(label))
    sharp_dot = rational_dot_quadratic(sharp_direction, coefficient[:3])
    transverse_squared = quadratic_dot(
        coefficient[:3], coefficient[:3], radicand
    )
    sharp_squared = rational_dot(sharp_direction, sharp_direction)
    alignment_squared = q_divide(
        q_multiply(sharp_dot, sharp_dot, radicand),
        q_scale(sharp_squared, transverse_squared),
        radicand,
    )
    return {
        "label": list(label),
        "radius": radius(label),
        "charge": str(charge(label)),
        "offset": [str(component) for component in offset(label)],
        "coefficient": [q_record(component, radicand) for component in coefficient],
        "constraint": q_record(constraint(label, coefficient), radicand),
        "coneModeNormDecimal": coefficient_mode_norm(coefficient, radicand),
        "sharpDirectionNumerator": [str(component) for component in sharp_direction],
        "sharpProjection": q_record(sharp_dot, radicand),
        "sharpProjectionIsNonzero": not q_is_zero(sharp_dot),
        "longitudinalJetIsNonzero": not q_is_zero(coefficient[3]),
        "squaredCosineWithSharpDirection": q_record(alignment_squared, radicand),
    }


def float_cone_bilinear(
    left_label: Label,
    left: tuple[float, float, float, float],
    right_label: Label,
    right: tuple[float, float, float, float],
) -> tuple[float, float, float, float]:
    output_label = label_add(left_label, right_label)
    beta_right = offset(right_label)
    scalar = sum(float(beta_right[index]) * left[index] for index in range(3))
    scalar += float(charge(right_label)) * left[3]
    output_beta = offset(output_label)
    output_charge = charge(output_label)
    transverse = tuple(scalar * right[index] for index in range(3))
    longitudinal = -sum(
        float(output_beta[index]) * transverse[index] for index in range(3)
    ) / float(output_charge)
    return transverse + (longitudinal,)  # type: ignore[return-value]


def sharp_benchmark(left_label: Label, right_label: Label) -> float:
    directions = []
    for label in (left_label, right_label):
        numerator = rational_cross(DIRECTION, offset(label))
        length = math.sqrt(float(rational_dot(numerator, numerator)))
        directions.append(tuple(float(component) / length for component in numerator))
    left = directions[0] + (0.0,)
    right = directions[1] + (0.0,)
    ordered_left = float_cone_bilinear(left_label, left, right_label, right)
    ordered_right = float_cone_bilinear(right_label, right, left_label, left)
    symmetrized = tuple(
        ordered_left[index] + ordered_right[index] for index in range(4)
    )
    return math.sqrt(sum(component * component for component in symmetrized[:3])) + abs(
        symmetrized[3]
    )


def finite_initial_field(
    center: dict[str, Rational],
    delta: float,
) -> dict[Label, tuple[float, float, float]]:
    p_value, q_value, x_value = map(float, (center["p"], center["q"], center["x"]))
    charts = (p_value, -p_value, q_value, -q_value)
    amplitudes = (1.0, 1.0, math.sqrt(x_value) / 2.0, math.sqrt(x_value) / 2.0)
    positive = []
    for index in range(4):
        numerator = tuple(
            float(BASE_TRANSVERSE[index][axis])
            + delta * float(BASE_LONGITUDINAL[index] / 3)
            + charts[index]
            * (
                float(CHART_TRANSVERSE[index][axis])
                + delta * delta * float(CHART_SECOND_ORDER[index][axis])
            )
            for axis in range(3)
        )
        length = math.sqrt(sum(component * component for component in numerator))
        positive.append(
            tuple(amplitudes[index] * component / length for component in numerator)
        )
    return {
        label: coefficient
        for label, coefficient in zip(INITIAL_LABELS, positive + positive, strict=True)
    }


def finite_wavevector(label: Label, delta: float) -> tuple[float, float, float]:
    label_charge = float(charge(label)) / delta
    label_offset = offset(label)
    return tuple(label_charge + float(label_offset[index]) for index in range(3))


def finite_bilinear(
    left_label: Label,
    left: tuple[float, float, float],
    right_label: Label,
    right: tuple[float, float, float],
    delta: float,
) -> tuple[Label, tuple[float, float, float]]:
    output_label = label_add(left_label, right_label)
    output_wavevector = finite_wavevector(output_label, delta)
    output_squared = sum(component * component for component in output_wavevector)
    if output_squared == 0:
        return output_label, (0.0, 0.0, 0.0)
    right_wavevector = finite_wavevector(right_label, delta)
    scalar = sum(right_wavevector[index] * left[index] for index in range(3))
    raw = tuple(scalar * component for component in right)
    parallel = sum(output_wavevector[index] * raw[index] for index in range(3))
    projected = tuple(
        raw[index] - output_wavevector[index] * parallel / output_squared
        for index in range(3)
    )
    return output_label, projected


def finite_taylor(
    center: dict[str, Rational],
    delta: float,
    maximum_order: int,
) -> list[dict[Label, tuple[float, float, float]]]:
    coefficients = [finite_initial_field(center, delta)]
    for next_order in range(1, maximum_order + 1):
        output: dict[Label, tuple[float, float, float]] = {}
        for left_order in range(next_order):
            right_order = next_order - 1 - left_order
            for left_label, left in coefficients[left_order].items():
                for right_label, right in coefficients[right_order].items():
                    output_label, value = finite_bilinear(
                        left_label, left, right_label, right, delta
                    )
                    old = output.get(output_label, (0.0, 0.0, 0.0))
                    output[output_label] = tuple(
                        old[index] - value[index] / next_order for index in range(3)
                    )
        coefficients.append(output)
    return coefficients


def finite_convergence_records(
    center: dict[str, Rational],
    radicand: Rational,
    targets: tuple[tuple[str, Label, int, ConeCoefficient], ...],
    levels: tuple[int, ...] = (3, 5, 7),
) -> list[dict[str, object]]:
    pump_scale = 1.0 / math.sqrt(6.0 * (1.0 + float(center["p"]) ** 2 / 12.0))
    records = []
    for level in levels:
        delta = 4.0 ** (-level)
        coefficients = finite_taylor(center, delta, MAXIMUM_ORDER)
        target_records = []
        for name, label, order, cone_value in targets:
            finite_value = coefficients[order][label]
            scaled = tuple(component / pump_scale ** (order + 1) for component in finite_value)
            cone_transverse = tuple(q_float(value, radicand) for value in cone_value[:3])
            cone_longitudinal = q_float(cone_value[3], radicand)
            transverse_error = math.sqrt(
                sum((scaled[index] - cone_transverse[index]) ** 2 for index in range(3))
            ) / math.sqrt(sum(component * component for component in cone_transverse))
            finite_longitudinal = sum(scaled) / delta
            longitudinal_error = abs(finite_longitudinal - cone_longitudinal) / abs(
                cone_longitudinal
            )
            target_records.append(
                {
                    "name": name,
                    "label": list(label),
                    "timeOrder": order,
                    "relativeTransverseError": transverse_error,
                    "relativeLongitudinalError": longitudinal_error,
                }
            )
        records.append({"level": level, "delta": delta, "targets": target_records})
    return records


def audit(show_progress: bool = False) -> dict[str, object]:
    started = time.perf_counter()
    center, root_radius, root_hash = load_root_center()
    pump_norm_squared = Rational(1) + center["p"] * center["p"] / 12
    catalyst_norm_squared = Rational(1) + center["q"] * center["q"] / 3
    radicand = center["x"] * pump_norm_squared / (4 * catalyst_norm_squared)
    if radicand <= 0:
        raise AssertionError("the catalyst-to-pump weight must be real and nonzero")
    if rational_is_square(radicand):
        raise AssertionError("the selected quadratic generator is unexpectedly rational")
    progress(show_progress, started, "loaded the R0.20 rational root center")

    initial = initial_field(center, radicand)
    coefficients, support = pure_nonlinear_taylor(
        initial,
        radicand,
        MAXIMUM_ORDER,
        show_progress,
        started,
    )

    left_label, right_label, output_label = sharp_labels(SHARPNESS_PARAMETER)
    left_order = radius(left_label) - 1
    right_order = radius(right_label) - 1
    output_order = radius(output_label) - 1
    left = coefficients[left_order].get(left_label)
    right = coefficients[right_order].get(right_label)
    full_output = coefficients[output_order].get(output_label)
    if left is None or right is None or full_output is None:
        raise AssertionError("an N=2 sharp-family coefficient is unexpectedly absent")

    _, left_right = cone_bilinear(
        left_label, left, right_label, right, radicand
    )
    _, right_left = cone_bilinear(
        right_label, right, left_label, left, radicand
    )
    symmetrized = coefficient_add(left_right, right_left)
    root_contribution = coefficient_scale(Rational(-1, output_order), symmetrized)
    input_norm_product = coefficient_mode_norm(left, radicand) * coefficient_mode_norm(
        right, radicand
    )
    generated_gain = coefficient_mode_norm(symmetrized, radicand) / input_norm_product
    benchmark_gain = sharp_benchmark(left_label, right_label)

    finite_convergence = finite_convergence_records(
        center,
        radicand,
        (
            ("left", left_label, left_order, left),
            ("right", right_label, right_order, right),
            ("fullOutput", output_label, output_order, full_output),
        ),
    )
    progress(show_progress, started, "checked finite-shell convergence at levels 3, 5, and 7")

    root_transverse = [q_float(value, radicand) for value in root_contribution[:3]]
    full_transverse = [q_float(value, radicand) for value in full_output[:3]]
    root_transverse_norm = math.sqrt(sum(value * value for value in root_transverse))
    full_transverse_norm = math.sqrt(sum(value * value for value in full_transverse))
    root_full_dot = sum(
        root_transverse[index] * full_transverse[index] for index in range(3)
    )

    progress(show_progress, started, "finished the exact N=2 generated-subspace audit")
    return {
        "scope": {
            "result": "exact first encounter with the R0.22 sharp labels in the R0.20 generated Taylor field",
            "proved": [
                "the N=2 sharp labels occur at their minimal Taylor orders",
                "both generated input coefficients have nonzero projection on the R0.22 sharp transverse directions",
                "both generated input coefficients also have nonzero longitudinal jets",
                "the two corresponding ordered root interactions do not cancel exactly",
            ],
            "notClaimed": [
                "uniform nonvanishing throughout the R0.20 root box",
                "an all-N asymptotic estimate for the generated coefficients",
                "closure with only one analytic-radius derivative",
                "a Navier--Stokes regularity or singularity result",
            ],
        },
        "root": {
            "center": {key: str(value) for key, value in center.items()},
            "boxRadius": str(root_radius),
            "certificate": str(ROOT_CERTIFICATE),
            "certificateSha256": root_hash,
        },
        "quadraticField": {
            "generator": "t = sqrt(x (1+p^2/12) / (4 (1+q^2/3)))",
            "radicand": str(radicand),
            "radicandIsRationalSquare": rational_is_square(radicand),
            "generatorDecimal": math.sqrt(float(radicand)),
            "commonPumpScaleOmitted": "1 / sqrt(6 (1+p^2/12)) per leaf",
            "reason": "the omitted scale is common at each fixed Taylor order and does not change zeros, directions, or same-order ratios",
        },
        "recurrence": {
            "equation": "(k+1) U_(k+1) = -sum_(j=0)^k B(U_j,U_(k-j))",
            "maximumTimeOrder": MAXIMUM_ORDER,
            "pureNonlinear": True,
            "support": support,
            "finiteShellConvergence": finite_convergence,
        },
        "sharpFamilyFirstEncounter": {
            "parameter": SHARPNESS_PARAMETER,
            "orders": {
                "left": left_order,
                "right": right_order,
                "output": output_order,
            },
            "left": coefficient_record(left_label, left, radicand),
            "right": coefficient_record(right_label, right, radicand),
            "fullOutput": coefficient_record(output_label, full_output, radicand),
            "symmetrizedRootOperatorOutput": coefficient_record(
                output_label, symmetrized, radicand
            ),
            "timeOrderTenRootContribution": coefficient_record(
                output_label, root_contribution, radicand
            ),
            "comparison": {
                "generatedSymmetrizedOperatorGain": generated_gain,
                "generatedGainOverRadiusProduct": generated_gain
                / (radius(left_label) * radius(right_label)),
                "R022SharpPolarizationGainAtN2": benchmark_gain,
                "generatedToSharpGainRatio": generated_gain / benchmark_gain,
                "rootContributionToFullOutputTransverseNorm": root_transverse_norm
                / full_transverse_norm,
                "rootContributionToFullOutputModeNorm": coefficient_mode_norm(
                    root_contribution, radicand
                )
                / coefficient_mode_norm(full_output, radicand),
                "squaredCosineRootContributionVsFullOutput": (
                    root_full_dot * root_full_dot
                    / (root_transverse_norm**2 * full_transverse_norm**2)
                ),
            },
        },
        "environment": {
            "python": platform.python_version(),
            "platform": platform.platform(),
            "arithmetic": f"{RATIONAL_BACKEND} over a real quadratic field",
        },
        "git": git_source_state(),
        "wallSeconds": time.perf_counter() - started,
    }


def validate(result: dict[str, object]) -> None:
    encounter = result["sharpFamilyFirstEncounter"]
    assert encounter["orders"] == {"left": 5, "right": 4, "output": 10}
    assert encounter["left"]["constraint"]["isExactlyZero"] is True
    assert encounter["right"]["constraint"]["isExactlyZero"] is True
    assert encounter["fullOutput"]["constraint"]["isExactlyZero"] is True
    assert encounter["left"]["sharpProjectionIsNonzero"] is True
    assert encounter["right"]["sharpProjectionIsNonzero"] is True
    assert encounter["left"]["longitudinalJetIsNonzero"] is True
    assert encounter["right"]["longitudinalJetIsNonzero"] is True
    assert (
        encounter["symmetrizedRootOperatorOutput"]["coefficient"][0][
            "isExactlyZero"
        ]
        is False
    )
    comparison = encounter["comparison"]
    assert 0.004 < comparison["generatedToSharpGainRatio"] < 0.005
    assert 0.0004 < comparison["rootContributionToFullOutputTransverseNorm"] < 0.0006
    support = result["recurrence"]["support"]
    assert support[-1]["timeOrder"] == 10
    assert support[-1]["supportSize"] == 1720
    assert result["quadraticField"]["radicandIsRationalSquare"] is False
    final_convergence = result["recurrence"]["finiteShellConvergence"][-1]
    for target in final_convergence["targets"]:
        assert target["relativeTransverseError"] < 0.002
        assert target["relativeLongitudinalError"] < 0.002


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--pretty", action="store_true")
    parser.add_argument("--progress", action="store_true")
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    result = audit(show_progress=arguments.progress)
    if arguments.check:
        validate(result)
    serialized = json.dumps(
        result,
        ensure_ascii=False,
        indent=2 if arguments.pretty else None,
        sort_keys=True,
    )
    if arguments.output:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(serialized + "\n")
    print(serialized)


if __name__ == "__main__":
    main()
