#!/usr/bin/env python3
"""Polish and certify isolated positive roots of the R0.20 system.

The input candidates are generated by ``positive_region_multistart_scan.py``.
This script independently reloads the exact rational saturated stationary
polynomials, refines each candidate with arbitrary-precision Newton iteration,
and applies an exact rational Krawczyk bound on a small box in ``(p,q,x)``.

Each successful certificate proves that its box contains exactly one zero of
the saturated stationary system.  It does not prove that the listed boxes
contain every positive zero; that requires a separate whole-domain exclusion.
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from decimal import Decimal, localcontext
from fractions import Fraction
import gzip
import hashlib
import json
from pathlib import Path
import sys
import time

import mpmath as mp
import numpy as np


SYSTEM_NAMES = (
    "saturated_stationary_p",
    "saturated_stationary_q",
    "saturated_stationary_x",
)
Rational = Fraction
Term = tuple[tuple[int, int, int], Rational]


def emit(stage: str, started: float, **fields: object) -> None:
    record = {
        "timestampUtc": datetime.now(timezone.utc).isoformat(),
        "elapsedSeconds": round(time.perf_counter() - started, 3),
        "stage": stage,
        **fields,
    }
    print(json.dumps(record, separators=(",", ":")), file=sys.stderr, flush=True)


def load_cache(path: Path) -> dict[str, object]:
    with gzip.open(path, "rt", encoding="utf-8") as stream:
        payload = json.load(stream)
    if payload.get("schemaVersion") != 2:
        raise ValueError("R0.20 exact cache schema version 2 is required")
    return payload


def parse_terms(rows: list[list[object]]) -> list[Term]:
    return [
        (
            (int(row[0]), int(row[1]), int(row[2])),
            Rational(int(row[3]), int(row[4])),
        )
        for row in rows
    ]


def derivative(terms: list[Term], axis: int) -> list[Term]:
    result: list[Term] = []
    for powers, coefficient in terms:
        power = powers[axis]
        if power:
            reduced = list(powers)
            reduced[axis] -= 1
            result.append((tuple(reduced), coefficient * power))
    return result


def mp_value(terms: list[Term], point: tuple[mp.mpf, mp.mpf, mp.mpf]) -> mp.mpf:
    degrees = tuple(max((powers[axis] for powers, _ in terms), default=0) for axis in range(3))
    powers = [[mp.mpf(1)] * (degree + 1) for degree in degrees]
    for axis in range(3):
        for exponent in range(1, degrees[axis] + 1):
            powers[axis][exponent] = powers[axis][exponent - 1] * point[axis]
    return mp.fsum(
        mp.mpf(coefficient.numerator)
        / coefficient.denominator
        * powers[0][monomial[0]]
        * powers[1][monomial[1]]
        * powers[2][monomial[2]]
        for monomial, coefficient in terms
    )


def rational_value(terms: list[Term], point: tuple[Rational, Rational, Rational]) -> Rational:
    degrees = tuple(max((powers[axis] for powers, _ in terms), default=0) for axis in range(3))
    powers = [[Rational(1)] * (degree + 1) for degree in degrees]
    for axis in range(3):
        for exponent in range(1, degrees[axis] + 1):
            powers[axis][exponent] = powers[axis][exponent - 1] * point[axis]
    return sum(
        (
            coefficient
            * powers[0][monomial[0]]
            * powers[1][monomial[1]]
            * powers[2][monomial[2]]
            for monomial, coefficient in terms
        ),
        start=Rational(0),
    )


def absolute_bound(terms: list[Term], upper: tuple[Rational, Rational, Rational]) -> Rational:
    degrees = tuple(max((powers[axis] for powers, _ in terms), default=0) for axis in range(3))
    powers = [[Rational(1)] * (degree + 1) for degree in degrees]
    for axis in range(3):
        for exponent in range(1, degrees[axis] + 1):
            powers[axis][exponent] = powers[axis][exponent - 1] * upper[axis]
    return sum(
        (
            abs(coefficient)
            * powers[0][monomial[0]]
            * powers[1][monomial[1]]
            * powers[2][monomial[2]]
            for monomial, coefficient in terms
        ),
        start=Rational(0),
    )


def invert(matrix: list[list[Rational]]) -> list[list[Rational]]:
    size = len(matrix)
    augmented = [
        list(row) + [Rational(int(row_index == column)) for column in range(size)]
        for row_index, row in enumerate(matrix)
    ]
    for column in range(size):
        pivot = next((row for row in range(column, size) if augmented[row][column]), None)
        if pivot is None:
            raise ArithmeticError("singular center Jacobian")
        augmented[column], augmented[pivot] = augmented[pivot], augmented[column]
        value = augmented[column][column]
        augmented[column] = [entry / value for entry in augmented[column]]
        for row in range(size):
            if row == column:
                continue
            factor = augmented[row][column]
            if factor:
                augmented[row] = [
                    augmented[row][index] - factor * augmented[column][index]
                    for index in range(2 * size)
                ]
    return [row[size:] for row in augmented]


def decimal_string(value: Rational, precision: int = 70) -> str:
    with localcontext() as context:
        context.prec = precision
        return str(Decimal(value.numerator) / Decimal(value.denominator))


def digest(value: Rational) -> str:
    return hashlib.sha256(f"{value.numerator}/{value.denominator}".encode("ascii")).hexdigest()


def polish(
    functions: list[list[Term]],
    jacobian: list[list[list[Term]]],
    initial: tuple[str, str, str],
    digits: int,
) -> tuple[tuple[mp.mpf, mp.mpf, mp.mpf], int, mp.mpf]:
    mp.mp.dps = digits
    point = mp.matrix([mp.mpf(value) for value in initial])
    tolerance = mp.power(10, -(digits - 18))
    for iteration in range(1, 31):
        point_tuple = tuple(point[index] for index in range(3))
        values = mp.matrix([mp_value(function, point_tuple) for function in functions])
        matrix = mp.matrix(
            [[mp_value(jacobian[row][column], point_tuple) for column in range(3)] for row in range(3)]
        )
        delta = mp.lu_solve(matrix, values)
        point -= delta
        if max(abs(delta[index]) for index in range(3)) < tolerance:
            residual = max(
                abs(mp_value(function, tuple(point[index] for index in range(3))))
                for function in functions
            )
            return tuple(point[index] for index in range(3)), iteration, residual
    raise ArithmeticError("high-precision Newton iteration did not converge")


def krawczyk(
    functions: list[list[Term]],
    jacobian: list[list[list[Term]]],
    center: tuple[Rational, Rational, Rational],
    radius: Rational,
) -> dict[str, object]:
    radii = (radius, radius, radius)
    upper = tuple(abs(center[index]) + radius for index in range(3))
    center_values = [rational_value(function, center) for function in functions]
    jacobian_center = [
        [rational_value(jacobian[row][column], center) for column in range(3)]
        for row in range(3)
    ]
    inverse = invert(jacobian_center)
    variation: list[list[Rational]] = []
    for row in range(3):
        variation_row = []
        for column in range(3):
            variation_row.append(
                sum(
                    (
                        absolute_bound(derivative(jacobian[row][column], axis), upper)
                        * radii[axis]
                        for axis in range(3)
                    ),
                    start=Rational(0),
                )
            )
        variation.append(variation_row)
    contraction_matrix = [
        [
            sum(
                (abs(inverse[row][inner]) * variation[inner][column] for inner in range(3)),
                start=Rational(0),
            )
            for column in range(3)
        ]
        for row in range(3)
    ]
    shift = [
        -sum(
            (inverse[row][column] * center_values[column] for column in range(3)),
            start=Rational(0),
        )
        for row in range(3)
    ]
    image_radii = [
        sum(
            (contraction_matrix[row][column] * radii[column] for column in range(3)),
            start=Rational(0),
        )
        for row in range(3)
    ]
    ratios = [(abs(shift[index]) + image_radii[index]) / radius for index in range(3)]
    row_sums = [sum(row, start=Rational(0)) for row in contraction_matrix]
    return {
        "method": "exact rational Krawczyk bound",
        "radius": str(radius),
        "boxDecimal": [
            [decimal_string(center[index] - radius), decimal_string(center[index] + radius)]
            for index in range(3)
        ],
        "strictInteriorInclusion": all(value < 1 for value in ratios),
        "contractionCertified": all(value < 1 for value in row_sums),
        "inclusionRatios": [float(value) for value in ratios],
        "contractionRowSums": [float(value) for value in row_sums],
        "centerResidualDigests": [digest(value) for value in center_values],
    }


def nonzero_box(terms: list[Term], center: tuple[Rational, Rational, Rational], radius: Rational) -> dict[str, object]:
    value = rational_value(terms, center)
    upper = tuple(abs(entry) + radius for entry in center)
    variation = sum(
        (
            absolute_bound(derivative(terms, axis), upper) * radius
            for axis in range(3)
        ),
        start=Rational(0),
    )
    lower_abs = abs(value) - variation
    return {
        "certifiedNonzero": lower_abs > 0,
        "centerSign": 1 if value > 0 else -1 if value < 0 else 0,
        "absoluteLowerBoundDecimal": decimal_string(lower_abs),
        "centerDigest": digest(value),
    }


def quotient_hessian_certificate(
    target: list[Term],
    external: list[Term],
    stationary: list[list[Term]],
    center: tuple[Rational, Rational, Rational],
    radius: Rational,
) -> dict[str, object]:
    """Certify the inertia of E/T at the unique root in the box."""

    upper = tuple(abs(entry) + radius for entry in center)
    target_center = rational_value(target, center)
    target_variation = sum(
        (
            absolute_bound(derivative(target, axis), upper) * radius
            for axis in range(3)
        ),
        start=Rational(0),
    )
    target_interval = (
        target_center - target_variation,
        target_center + target_variation,
    )
    if target_interval[0] <= 0:
        raise AssertionError("the target numerator is not positive on the root box")

    stationary_jacobian = [
        [derivative(stationary[row], column) for column in range(3)]
        for row in range(3)
    ]
    raw_centers = [
        [rational_value(stationary_jacobian[row][column], center) for column in range(3)]
        for row in range(3)
    ]
    raw_variations = [
        [
            sum(
                (
                    absolute_bound(derivative(stationary_jacobian[row][column], axis), upper)
                    * radius
                    for axis in range(3)
                ),
                start=Rational(0),
            )
            for column in range(3)
        ]
        for row in range(3)
    ]
    denominator_interval = (target_interval[0] ** 2, target_interval[1] ** 2)
    entry_intervals: list[list[tuple[Rational, Rational]]] = []
    for row in range(3):
        interval_row = []
        for column in range(3):
            numerator = (
                raw_centers[row][column] - raw_variations[row][column],
                raw_centers[row][column] + raw_variations[row][column],
            )
            candidates = [
                numerator[side] / denominator_interval[denominator_side]
                for side in range(2)
                for denominator_side in range(2)
            ]
            interval_row.append((min(candidates), max(candidates)))
        entry_intervals.append(interval_row)

    # At a stationary point this Jacobian quotient is symmetric.  Use one
    # symmetric rational center and an error that contains both directed
    # interval evaluations.
    hessian_center: list[list[Rational]] = [[Rational(0)] * 3 for _ in range(3)]
    hessian_error: list[list[Rational]] = [[Rational(0)] * 3 for _ in range(3)]
    for row in range(3):
        for column in range(row, 3):
            central = Rational(1, 2) * (
                raw_centers[row][column] + raw_centers[column][row]
            ) / target_center**2
            lows = [entry_intervals[row][column][0], entry_intervals[column][row][0]]
            highs = [entry_intervals[row][column][1], entry_intervals[column][row][1]]
            error = max(central - min(lows), max(highs) - central)
            hessian_center[row][column] = hessian_center[column][row] = central
            hessian_error[row][column] = hessian_error[column][row] = error

    margins = []
    for row in range(3):
        diagonal_lower = hessian_center[row][row] - hessian_error[row][row]
        off_diagonal_upper = sum(
            (
                abs(hessian_center[row][column]) + hessian_error[row][column]
                for column in range(3)
                if column != row
            ),
            start=Rational(0),
        )
        margins.append(diagonal_lower - off_diagonal_upper)
    positive_definite = all(value > 0 for value in margins)

    floating_center = np.array(
        [[float(value) for value in row] for row in hessian_center],
        dtype=np.float64,
    )
    eigenvalues, eigenvectors = np.linalg.eigh(floating_center)
    directions = []
    direction_signs = []
    for column in range(3):
        vector = tuple(
            Rational(int(round(1.0e9 * eigenvectors[row, column])), 10**9)
            for row in range(3)
        )
        central = sum(
            (
                vector[row] * hessian_center[row][inner] * vector[inner]
                for row in range(3)
                for inner in range(3)
            ),
            start=Rational(0),
        )
        error = sum(
            (
                abs(vector[row] * vector[inner]) * hessian_error[row][inner]
                for row in range(3)
                for inner in range(3)
            ),
            start=Rational(0),
        )
        sign = "positive" if central - error > 0 else "negative" if central + error < 0 else "unresolved"
        direction_signs.append(sign)
        directions.append(
            {
                "vector": [str(value) for value in vector],
                "sign": sign,
                "lowerDecimal": float(central - error),
                "upperDecimal": float(central + error),
            }
        )
    indefinite = "positive" in direction_signs and "negative" in direction_signs
    classification = (
        "strict local minimum of external/target; strict local maximum of target fraction"
        if positive_definite
        else "nondegenerate saddle of both quotient and target fraction"
        if indefinite and "unresolved" not in direction_signs
        else "unresolved"
    )

    target_mp = mp_value(target, tuple(mp.mpf(entry.numerator) / entry.denominator for entry in center))
    external_mp = mp_value(external, tuple(mp.mpf(entry.numerator) / entry.denominator for entry in center))
    quotient = external_mp / target_mp
    fraction = 1 / (1 + quotient)
    return {
        "classification": classification,
        "targetPositiveOnBox": True,
        "externalOverTarget": mp.nstr(quotient, 70),
        "targetFraction": mp.nstr(fraction, 70),
        "targetFractionPercent": mp.nstr(100 * fraction, 50),
        "hessianEigenvaluesAtBoxCenter": [float(value) for value in eigenvalues],
        "strictDiagonalDominanceMargins": [float(value) for value in margins],
        "positiveDefiniteCertified": positive_definite,
        "indefiniteCertified": indefinite,
        "rationalTestDirections": directions,
        "entryErrorUpperBounds": [
            [float(value) for value in row] for row in hessian_error
        ],
    }


def read_candidates(path: Path) -> list[tuple[str, str, str]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    header = lines[0].split("\t")
    indices = [header.index(name) for name in ("p", "q", "x")]
    return [tuple(row[index] for index in indices) for row in (line.split("\t") for line in lines[1:] if line)]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--candidates", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--digits", type=int, default=90)
    parser.add_argument("--center-digits", type=int, default=55)
    parser.add_argument("--radius-exponent", type=int, default=45)
    arguments = parser.parse_args()
    started = time.perf_counter()

    cache = load_cache(arguments.cache)
    polynomials = cache["polynomials"]
    functions = [parse_terms(polynomials[name]) for name in SYSTEM_NAMES]
    jacobian = [[derivative(function, axis) for axis in range(3)] for function in functions]
    target = parse_terms(polynomials["target"])
    external = parse_terms(polynomials["external"])
    quotient_stationary = [
        parse_terms(polynomials[f"stationary_{name}"])
        for name in ("p", "q", "x")
    ]
    target_factor = parse_terms(polynomials["target_square_factor"])
    candidates = read_candidates(arguments.candidates)
    emit("loaded exact system", started, candidates=len(candidates))

    records = []
    radius = Rational(1, 10**arguments.radius_exponent)
    for index, initial in enumerate(candidates, start=1):
        root, iterations, residual = polish(functions, jacobian, initial, arguments.digits)
        center = tuple(
            Rational(mp.nstr(value, arguments.center_digits, strip_zeros=False))
            for value in root
        )
        emit("polished candidate", started, index=index, iterations=iterations)
        certificate = krawczyk(functions, jacobian, center, radius)
        factor_check = nonzero_box(target_factor, center, radius)
        hessian = quotient_hessian_certificate(
            target,
            external,
            quotient_stationary,
            center,
            radius,
        )
        if not certificate["strictInteriorInclusion"] or not certificate["contractionCertified"]:
            raise AssertionError(f"candidate {index} failed Krawczyk inclusion")
        if not factor_check["certifiedNonzero"]:
            raise AssertionError(f"candidate {index} intersects the target-zero set")
        records.append(
            {
                "index": index,
                "polishedRoot": {
                    name: mp.nstr(root[axis], arguments.digits - 10)
                    for axis, name in enumerate(("p", "q", "x"))
                },
                "newtonIterations": iterations,
                "absoluteResidual": mp.nstr(residual, 12),
                "stationarySystemCertificate": certificate,
                "targetSquareFactor": factor_check,
                "objectiveAndHessian": hessian,
            }
        )
        emit("certified candidate", started, index=index)

    result = {
        "schemaVersion": 1,
        "scope": "isolated positive stationary-root certificates",
        "proofStatus": "existence and uniqueness in each listed box; not whole-domain completeness",
        "variables": ["p", "q", "x"],
        "configuration": {
            "cache": str(arguments.cache.resolve()),
            "candidates": str(arguments.candidates.resolve()),
            "digits": arguments.digits,
            "centerDigits": arguments.center_digits,
            "radiusExponent": arguments.radius_exponent,
        },
        "roots": records,
        "wallSeconds": time.perf_counter() - started,
    }
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    emit("all candidate certificates completed", started, roots=len(records))


if __name__ == "__main__":
    main()
