#!/usr/bin/env python3
"""Two-shell Fourier--Taylor audit for the cone polarization relay.

The initial real Fourier polynomial at shell ``n`` contains

    P_(n-1), Q_(n-1), epsilon b_n, epsilon d_n

and their conjugates, with the polarizations constructed in R0.11.  The
script computes two different degree-five Taylor recursions:

* the full recursion keeps every frequency generated by the Navier--Stokes
  quadratic term;
* the relay recursion projects after every operation onto the eight named
  frequency pairs in the intended two-shell network.

Time is normalized by ``tau = 4^(2n) t``.  In this normalization the heat
multiplier is ``-|k|^2 / 4^(2n)``.  The nonlinear coefficient used below is
one.  This is the exact Navier--Stokes normalization when the physical
Fourier amplitudes are ``4^(2n)`` times the amplitudes in this file.  At the
smaller single-mode scaling ``4^n`` the nonlinear coefficient is ``4^(-n)``.
Thus the coefficient-one calculation is also an effective envelope model
for any future dense-packet construction, but no dense-packet reduction is
asserted here.

Taylor coefficients use the ordinary-power convention

    u(tau) = sum_m U_m tau^m,

so

    (m+1) U_(m+1) = L U_m - sum_(r+s=m) B(U_r,U_s).

The computations are finite-dimensional identities for a Fourier polynomial.
They do not control the Taylor remainder, build a dense packet, or prove any
Navier--Stokes regularity or singularity statement.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
from typing import Iterable

import numpy as np

from polarization_relay import (
    center_kernel,
    cross_gate_scalar,
    geometry,
    relay_polarizations,
    unit,
    wing_gate_scalar,
)


Wavevector = tuple[int, int, int]
Field = dict[Wavevector, np.ndarray]
ZERO = np.zeros(3, dtype=np.complex128)
PRUNE_TOLERANCE = 1.0e-8


def key(wavevector: Iterable[int]) -> Wavevector:
    """Convert an integer vector to a hashable Fourier key."""

    return tuple(int(component) for component in wavevector)  # type: ignore[return-value]


def negative(wavevector: Wavevector) -> Wavevector:
    """Return the opposite Fourier frequency."""

    return tuple(-component for component in wavevector)  # type: ignore[return-value]


def add_coefficient(field: Field, wavevector: Wavevector, value: np.ndarray) -> None:
    """Add one coefficient in place."""

    if wavevector == (0, 0, 0):
        return
    field[wavevector] = field.get(wavevector, ZERO.copy()) + value


def clean(field: Field, support: set[Wavevector] | None = None) -> Field:
    """Remove numerical zeros and, optionally, frequencies outside support."""

    return {
        wavevector: coefficient
        for wavevector, coefficient in field.items()
        if np.linalg.norm(coefficient) > PRUNE_TOLERANCE
        and (support is None or wavevector in support)
    }


def add_fields(*fields: Field) -> Field:
    """Add sparse Fourier fields."""

    result: Field = {}
    for field in fields:
        for wavevector, coefficient in field.items():
            add_coefficient(result, wavevector, coefficient)
    return clean(result)


def real_field(entries: Iterable[tuple[np.ndarray, np.ndarray]]) -> Field:
    """Build a real field from positive-frequency entries."""

    result: Field = {}
    for wavevector, coefficient in entries:
        frequency = key(wavevector)
        value = np.asarray(coefficient, dtype=np.complex128)
        add_coefficient(result, frequency, value)
        add_coefficient(result, negative(frequency), np.conjugate(value))
    return clean(result)


def bilinear(
    left: Field,
    right: Field,
    support: set[Wavevector] | None = None,
) -> Field:
    """Return P[(left dot grad) right] with Fourier multiplier +i."""

    raw: Field = {}
    for first_wavevector, first_coefficient in left.items():
        for second_wavevector, second_coefficient in right.items():
            output = tuple(
                first_wavevector[axis] + second_wavevector[axis]
                for axis in range(3)
            )
            if output == (0, 0, 0) or (
                support is not None and output not in support
            ):
                continue
            contribution = (
                1.0j
                * np.dot(second_wavevector, first_coefficient)
                * second_coefficient
            )
            add_coefficient(raw, output, contribution)

    projected: Field = {}
    for wavevector, coefficient in raw.items():
        frequency = np.asarray(wavevector, dtype=float)
        value = coefficient - frequency * (
            np.dot(frequency, coefficient) / np.dot(frequency, frequency)
        )
        add_coefficient(projected, wavevector, value)
    return clean(projected, support)


def cross_bilinear(left: Field, right: Field) -> Field:
    """Return B(left,right)+B(right,left)."""

    return add_fields(bilinear(left, right), bilinear(right, left))


def heat_operator(field: Field, level: int) -> Field:
    """Apply the dimensionless heat generator at shell level."""

    scale_squared = float(4 ** (2 * level))
    return {
        wavevector: -sum(component * component for component in wavevector)
        / scale_squared
        * coefficient
        for wavevector, coefficient in field.items()
    }


def hhalf_pairing(
    left: Field,
    right: Field,
    support: set[Wavevector] | None = None,
) -> float:
    """Return the real homogeneous H^(1/2) Fourier pairing."""

    common = set(left).intersection(right)
    if support is not None:
        common.intersection_update(support)
    return float(
        sum(
            np.linalg.norm(wavevector)
            * np.vdot(left[wavevector], right[wavevector]).real
            for wavevector in common
        )
    )


def line_scalar(value: np.ndarray, direction: np.ndarray) -> complex:
    """Return the coefficient on a unit complex direction."""

    return complex(np.vdot(unit(direction), value))


def line_defect(value: np.ndarray, direction: np.ndarray) -> float:
    """Return the Euclidean distance from a one-dimensional complex line."""

    normalized = unit(direction)
    scalar = np.vdot(normalized, value)
    return float(np.linalg.norm(value - scalar * normalized))


def perpendicular_basis(wavevector: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Return a deterministic real orthonormal basis of k-perp."""

    frequency = unit(np.asarray(wavevector, dtype=float))
    seed = np.asarray([1.0, 0.0, 0.0])
    if abs(np.dot(seed, frequency)) > 0.9:
        seed = np.asarray([0.0, 1.0, 0.0])
    first = unit(seed - np.dot(seed, frequency) * frequency)
    second = np.cross(frequency, first)
    return first, second


def pump_field(level: int) -> Field:
    """Return the two old-shell pump pairs."""

    previous = geometry(level - 1)
    return real_field(
        [
            (previous["P"], unit(previous["pi"])),
            (previous["Q"], unit(previous["theta"])),
        ]
    )


def catalyst_field(
    level: int,
    epsilon: float,
    b_polarization: np.ndarray | None = None,
    d_polarization: np.ndarray | None = None,
) -> Field:
    """Return the two current-shell catalyst pairs."""

    current = geometry(level)
    relay = relay_polarizations(level)
    b_direction = relay["B"] if b_polarization is None else b_polarization
    d_direction = relay["D"] if d_polarization is None else d_polarization
    return real_field(
        [
            (current["b"], epsilon * b_direction),
            (current["d"], epsilon * d_direction),
        ]
    )


def initial_field(
    level: int,
    epsilon: float,
    b_polarization: np.ndarray | None = None,
    d_polarization: np.ndarray | None = None,
) -> Field:
    """Return pumps plus catalysts and all conjugate modes."""

    return add_fields(
        pump_field(level),
        catalyst_field(level, epsilon, b_polarization, d_polarization),
    )


def relay_support(level: int) -> set[Wavevector]:
    """Return the signed frequency support of the intended two-shell relay."""

    previous = geometry(level - 1)
    current = geometry(level)
    following = geometry(level + 1)
    positive = [
        previous["P"],
        previous["Q"],
        current["b"],
        current["d"],
        current["a"],
        current["P"],
        current["Q"],
        following["a"],
    ]
    result = {key(wavevector) for wavevector in positive}
    result.update(negative(wavevector) for wavevector in tuple(result))
    return result


def taylor_coefficients(
    initial: Field,
    level: int,
    maximum_order: int = 5,
    nonlinear_strength: float = 1.0,
    support: set[Wavevector] | None = None,
) -> list[Field]:
    """Compute ordinary-power Taylor coefficients through maximum_order."""

    coefficients = [clean(initial, support)]
    for order in range(maximum_order):
        right_hand_side = heat_operator(coefficients[order], level)
        for left_order in range(order + 1):
            interaction = bilinear(
                coefficients[left_order],
                coefficients[order - left_order],
                support,
            )
            for wavevector, value in interaction.items():
                add_coefficient(
                    right_hand_side,
                    wavevector,
                    -nonlinear_strength * value,
                )
        coefficients.append(
            clean(
                {
                    wavevector: value / (order + 1)
                    for wavevector, value in right_hand_side.items()
                },
                support,
            )
        )
    return coefficients


def field_errors(field: Field) -> dict[str, float]:
    """Return maximum reality and divergence defects."""

    reality = 0.0
    divergence = 0.0
    for wavevector, coefficient in field.items():
        opposite = field.get(negative(wavevector), ZERO)
        reality = max(reality, float(np.linalg.norm(opposite - np.conjugate(coefficient))))
        divergence = max(
            divergence,
            float(abs(np.dot(wavevector, coefficient))),
        )
    return {"reality": reality, "divergence": divergence}


def first_nonlinear_record(level: int, epsilon: float) -> dict[str, float]:
    """Measure target and leakage in B(U_0,U_0), excluding the heat term."""

    current = geometry(level)
    pumps = pump_field(level)
    catalysts = catalyst_field(level, 1.0)
    pump_output = bilinear(pumps, pumps)
    linear_leakage = cross_bilinear(pumps, catalysts)
    quadratic_leakage = bilinear(catalysts, catalysts)
    target_support = {key(current["a"]), negative(key(current["a"]))}
    target_energy = hhalf_pairing(pump_output, pump_output, target_support)
    linear_ratio = hhalf_pairing(linear_leakage, linear_leakage) / target_energy
    quadratic_ratio = (
        hhalf_pairing(quadratic_leakage, quadratic_leakage) / target_energy
    )
    leakage_ratio = linear_ratio * epsilon**2 + quadratic_ratio * epsilon**4
    return {
        "linearCoefficient": linear_ratio,
        "quadraticCoefficient": quadratic_ratio,
        "epsilon": epsilon,
        "leakageOverTarget": leakage_ratio,
        "targetFraction": 1.0 / (1.0 + leakage_ratio),
    }


def catalyst_variation(level: int) -> dict[str, object]:
    """Optimize pump--catalyst leakage under fixed future wing gates."""

    previous = geometry(level - 1)
    current = geometry(level)
    a_polarization = unit(previous["eta"])
    bases = [
        *perpendicular_basis(current["b"]),
        *perpendicular_basis(current["d"]),
    ]
    pumps = pump_field(level)
    pump_output = bilinear(pumps, pumps)
    target_support = {key(current["a"]), negative(key(current["a"]))}
    target_energy = hhalf_pairing(pump_output, pump_output, target_support)

    leakage_directions = []
    for index, direction in enumerate(bases):
        wavevector = current["b"] if index < 2 else current["d"]
        leakage_directions.append(
            cross_bilinear(pumps, real_field([(wavevector, direction)]))
        )
    quadratic_form = np.asarray(
        [
            [
                hhalf_pairing(leakage_directions[row], leakage_directions[column])
                / target_energy
                for column in range(4)
            ]
            for row in range(4)
        ]
    )

    gate_map = np.zeros((2, 4))
    for index, direction in enumerate(bases):
        if index < 2:
            value = center_kernel(
                current["a"],
                current["b"],
                1.0j * a_polarization,
                direction,
            )
            gate_map[0, index] = np.vdot(unit(current["pi"]), value).real
        else:
            value = center_kernel(
                current["a"],
                current["d"],
                1.0j * a_polarization,
                direction,
            )
            gate_map[1, index] = np.vdot(unit(current["theta"]), value).real

    inverse_form = np.linalg.inv(quadratic_form)
    schur = gate_map @ inverse_form @ gate_map.T
    prescribed = np.full(2, wing_gate_scalar(level))
    unconstrained = (
        inverse_form @ gate_map.T @ np.linalg.solve(schur, prescribed)
    )

    one_mode_solutions: list[list[np.ndarray]] = []
    for row, coordinate_slice in [(0, slice(0, 2)), (1, slice(2, 4))]:
        functional = gate_map[row, coordinate_slice]
        closest = functional * prescribed[row] / np.dot(functional, functional)
        tangent = np.asarray([-functional[1], functional[0]])
        tangent = unit(tangent)
        radius = math.sqrt(max(0.0, 1.0 - np.dot(closest, closest)))
        one_mode_solutions.append(
            [closest + radius * tangent, closest - radius * tangent]
        )

    candidates = []
    for b_index, d_index in itertools.product(range(2), repeat=2):
        coordinates = np.concatenate(
            [
                one_mode_solutions[0][b_index],
                one_mode_solutions[1][d_index],
            ]
        )
        b_polarization = coordinates[0] * bases[0] + coordinates[1] * bases[1]
        d_polarization = coordinates[2] * bases[2] + coordinates[3] * bases[3]
        b_difference = center_kernel(
            current["a"],
            -current["b"],
            1.0j * a_polarization,
            b_polarization,
        )
        d_difference = center_kernel(
            current["a"],
            -current["d"],
            1.0j * a_polarization,
            d_polarization,
        )
        b_defect = float(np.linalg.norm(b_difference))
        d_defect = float(np.linalg.norm(d_difference))
        candidates.append(
            {
                "indices": [b_index, d_index],
                "linearLeakage": float(
                    coordinates @ quadratic_form @ coordinates
                ),
                "bDifferenceDefect": b_defect,
                "dDifferenceDefect": d_defect,
                "cancelledDifferenceCount": int(b_defect < 1.0e-6)
                + int(d_defect < 1.0e-6),
                "bPolarization": b_polarization,
                "dPolarization": d_polarization,
            }
        )
    candidates.sort(
        key=lambda record: (
            -int(record["cancelledDifferenceCount"]),
            float(record["linearLeakage"]),
        )
    )

    def public_candidate(record: dict[str, object]) -> dict[str, object]:
        return {
            "indices": record["indices"],
            "linearLeakage": record["linearLeakage"],
            "bDifferenceDefect": record["bDifferenceDefect"],
            "dDifferenceDefect": record["dDifferenceDefect"],
            "cancelledDifferenceCount": record["cancelledDifferenceCount"],
        }

    return {
        "eigenvalues": np.linalg.eigvalsh(quadratic_form).tolist(),
        "gateMap": gate_map.tolist(),
        "unconstrainedMinimum": float(
            unconstrained @ quadratic_form @ unconstrained
        ),
        "unconstrainedCatalystNorms": [
            float(np.linalg.norm(unconstrained[:2])),
            float(np.linalg.norm(unconstrained[2:])),
        ],
        "unitCandidates": [public_candidate(candidate) for candidate in candidates],
        "internalCandidates": candidates,
    }


def target_supports(level: int) -> dict[int, set[Wavevector]]:
    """Return the intended target frequencies at Taylor orders 1, 2, and 5."""

    current = geometry(level)
    following = geometry(level + 1)

    def signed(*wavevectors: np.ndarray) -> set[Wavevector]:
        positive = {key(wavevector) for wavevector in wavevectors}
        return positive.union(negative(wavevector) for wavevector in positive)

    return {
        1: signed(current["a"]),
        2: signed(current["P"], current["Q"]),
        5: signed(following["a"]),
    }


def taylor_record(
    level: int,
    epsilon: float,
    b_polarization: np.ndarray | None = None,
    d_polarization: np.ndarray | None = None,
) -> dict[str, object]:
    """Compare the full and projected-relay Taylor coefficients."""

    initial = initial_field(level, epsilon, b_polarization, d_polarization)
    full = taylor_coefficients(initial, level)
    relay = taylor_coefficients(initial, level, support=relay_support(level))
    current = geometry(level)
    following = geometry(level + 1)
    next_frequency = key(following["a"])
    next_direction = 1.0j * unit(current["eta"])
    full_value = full[5].get(next_frequency, ZERO)
    relay_value = relay[5].get(next_frequency, ZERO)
    targets = target_supports(level)

    fractions = {}
    for order, support in targets.items():
        total_energy = hhalf_pairing(full[order], full[order])
        target_energy = hhalf_pairing(full[order], full[order], support)
        fractions[str(order)] = {
            "targetEnergyFraction": target_energy / total_energy,
            "outsideOverTarget": (total_energy - target_energy) / target_energy,
        }

    previous_gate = cross_gate_scalar(level - 1)
    wing_gate = wing_gate_scalar(level)
    next_gate = cross_gate_scalar(level)
    directed_formula = (
        -next_gate * previous_gate**2 * wing_gate**2 * epsilon**2 / 20.0
    )
    full_scalar = line_scalar(full_value, next_direction).real
    relay_scalar = line_scalar(relay_value, next_direction).real
    return {
        "level": level,
        "epsilon": epsilon,
        "fullSupportCounts": [len(field) for field in full],
        "relaySupportCounts": [len(field) for field in relay],
        "targetFractions": fractions,
        "fullNextScalar": full_scalar,
        "fullNextCoefficientPerEpsilonSquared": full_scalar / epsilon**2,
        "fullNextLineDefect": line_defect(full_value, next_direction),
        "relayNextScalar": relay_scalar,
        "directedFormula": directed_formula,
        "fullOverDirected": full_scalar / directed_formula,
        "maximumRealityDefect": max(
            field_errors(field)["reality"] for field in full
        ),
        "maximumDivergenceDefect": max(
            field_errors(field)["divergence"] for field in full
        ),
    }


def alternative_record(level: int, epsilon: float) -> dict[str, object]:
    """Audit the least-leaking unit choice that restores one difference gate."""

    variation = catalyst_variation(level)
    internal = variation["internalCandidates"]
    alternatives = [
        candidate
        for candidate in internal
        if int(candidate["cancelledDifferenceCount"]) == 1
    ]
    selected = min(alternatives, key=lambda record: float(record["linearLeakage"]))
    record = taylor_record(
        level,
        epsilon,
        np.asarray(selected["bPolarization"]),
        np.asarray(selected["dPolarization"]),
    )
    return {
        "linearLeakage": selected["linearLeakage"],
        "bDifferenceDefect": selected["bDifferenceDefect"],
        "dDifferenceDefect": selected["dDifferenceDefect"],
        "fullNextCoefficientPerEpsilonSquared": record[
            "fullNextCoefficientPerEpsilonSquared"
        ],
        "fullNextLineDefectPerEpsilonSquared": float(
            record["fullNextLineDefect"]
        )
        / epsilon**2,
    }


def heat_rate_record(level: int) -> dict[str, float]:
    """Return the named parabolic heat multipliers."""

    previous = geometry(level - 1)
    current = geometry(level)
    following = geometry(level + 1)
    scale_squared = float(4 ** (2 * level))

    def rate(wavevector: np.ndarray) -> float:
        return float(np.dot(wavevector, wavevector) / scale_squared)

    return {
        "oldP": rate(previous["P"]),
        "oldQ": rate(previous["Q"]),
        "a": rate(current["a"]),
        "b": rate(current["b"]),
        "d": rate(current["d"]),
        "P": rate(current["P"]),
        "Q": rate(current["Q"]),
        "nextA": rate(following["a"]),
    }


def merge_mixture(terms: Iterable[tuple[float, float]]) -> list[tuple[float, float]]:
    """Combine equal exponential rates in a finite real mixture."""

    result: list[tuple[float, float]] = []
    for rate, coefficient in terms:
        for index, (old_rate, old_coefficient) in enumerate(result):
            if abs(rate - old_rate) < 1.0e-12:
                result[index] = (old_rate, old_coefficient + coefficient)
                break
        else:
            result.append((rate, coefficient))
    return [term for term in result if abs(term[1]) > 1.0e-14]


def multiply_mixtures(
    left: list[tuple[float, float]],
    right: list[tuple[float, float]],
) -> list[tuple[float, float]]:
    """Multiply two sums of decaying exponentials."""

    return merge_mixture(
        (left_rate + right_rate, left_value * right_value)
        for left_rate, left_value in left
        for right_rate, right_value in right
    )


def duhamel_mixture(
    forcing: list[tuple[float, float]],
    output_rate: float,
) -> list[tuple[float, float]]:
    """Solve y'+output_rate*y=forcing with y(0)=0."""

    terms = []
    for forcing_rate, coefficient in forcing:
        denominator = output_rate - forcing_rate
        if abs(denominator) < 1.0e-12:
            raise ValueError("Repeated heat rates require a polynomial-exponential term.")
        terms.append((forcing_rate, coefficient / denominator))
        terms.append((output_rate, -coefficient / denominator))
    return merge_mixture(terms)


def evaluate_mixture(mixture: list[tuple[float, float]], time: float) -> float:
    """Evaluate a real exponential mixture."""

    return float(
        sum(coefficient * math.exp(-rate * time) for rate, coefficient in mixture)
    )


def derivative_mixture(mixture: list[tuple[float, float]], time: float) -> float:
    """Evaluate the derivative of a real exponential mixture."""

    return float(
        sum(
            -rate * coefficient * math.exp(-rate * time)
            for rate, coefficient in mixture
        )
    )


def directed_heat_profile(
    level: int,
    epsilon: float,
    nonlinear_strength: float = 1.0,
) -> dict[str, object]:
    """Solve the one-way relay with exact heat semigroups.

    This triangular comparison system discards every reverse and external
    frequency edge.  Its value is a timing baseline, not an approximation
    theorem for the full Fourier evolution.
    """

    rates = heat_rate_record(level)
    previous_gate = cross_gate_scalar(level - 1)
    wing_gate = wing_gate_scalar(level)
    next_gate = cross_gate_scalar(level)
    gamma = nonlinear_strength

    pump_product = [
        (rates["oldP"] + rates["oldQ"], gamma * previous_gate)
    ]
    a_mixture = duhamel_mixture(pump_product, rates["a"])
    b_mixture = [(rates["b"], epsilon)]
    d_mixture = [(rates["d"], epsilon)]
    p_forcing = [
        (rate, gamma * wing_gate * coefficient)
        for rate, coefficient in multiply_mixtures(a_mixture, b_mixture)
    ]
    q_forcing = [
        (rate, gamma * wing_gate * coefficient)
        for rate, coefficient in multiply_mixtures(a_mixture, d_mixture)
    ]
    p_mixture = duhamel_mixture(p_forcing, rates["P"])
    q_mixture = duhamel_mixture(q_forcing, rates["Q"])
    next_forcing = [
        (rate, gamma * next_gate * coefficient)
        for rate, coefficient in multiply_mixtures(p_mixture, q_mixture)
    ]
    next_mixture = duhamel_mixture(next_forcing, rates["nextA"])

    grid = np.linspace(1.0e-4, 10.0, 100_001)
    values = np.asarray([evaluate_mixture(next_mixture, time) for time in grid])
    maximum_index = int(np.argmax(values))
    left = float(grid[max(0, maximum_index - 1)])
    right = float(grid[min(len(grid) - 1, maximum_index + 1)])
    left_derivative = derivative_mixture(next_mixture, left)
    right_derivative = derivative_mixture(next_mixture, right)
    if left_derivative > 0.0 and right_derivative < 0.0:
        for _ in range(80):
            middle = 0.5 * (left + right)
            if derivative_mixture(next_mixture, middle) > 0.0:
                left = middle
            else:
                right = middle
        maximum_time = 0.5 * (left + right)
    else:
        maximum_time = float(grid[maximum_index])

    maximum_value = evaluate_mixture(next_mixture, maximum_time)
    return {
        "maximumTime": maximum_time,
        "maximumAmplitude": maximum_value,
        "gammaFifthPowerNormalizedMaximum": maximum_value / gamma**5,
        "mixture": [
            {"rate": rate, "coefficient": coefficient}
            for rate, coefficient in next_mixture
        ],
    }


def leaf_count_solutions(level: int) -> list[list[int]]:
    """Enumerate six-leaf signed representations of a_(n+1)."""

    previous = geometry(level - 1)
    current = geometry(level)
    following = geometry(level + 1)
    generators = np.stack(
        [previous["P"], previous["Q"], current["b"], current["d"]],
        axis=1,
    )
    solutions = []
    for coefficients in itertools.product(range(-6, 7), repeat=4):
        minimum_leaves = sum(abs(value) for value in coefficients)
        if minimum_leaves > 6 or (6 - minimum_leaves) % 2:
            continue
        if np.array_equal(
            generators @ np.asarray(coefficients),
            following["a"],
        ):
            solutions.append(list(coefficients))
    return solutions


def audit(
    levels: Iterable[int] = range(2, 9),
    epsilon: float = 0.2,
) -> dict[str, object]:
    """Return the complete two-shell audit."""

    level_list = list(levels)
    records = []
    for level in level_list:
        variation = catalyst_variation(level)
        public_variation = {
            key_name: value
            for key_name, value in variation.items()
            if key_name != "internalCandidates"
        }
        records.append(
            {
                "level": level,
                "firstNonlinear": first_nonlinear_record(level, epsilon),
                "variation": public_variation,
                "taylor": taylor_record(level, epsilon),
                "heatRates": heat_rate_record(level),
                "directedHeatProfile": directed_heat_profile(level, epsilon),
            }
        )

    last_level = level_list[-1]
    return {
        "convention": {
            "time": "tau = 4^(2n) t",
            "series": "u(tau) = sum_m U_m tau^m",
            "equation": "du/dtau = L u - gamma B(u,u)",
            "gamma": 1.0,
            "epsilon": epsilon,
        },
        "records": records,
        "sixLeafSolutions": leaf_count_solutions(last_level),
        "leastLeakingOneDifferenceAlternative": alternative_record(
            last_level,
            epsilon,
        ),
    }


def validate(result: dict[str, object]) -> None:
    """Raise AssertionError if a published numerical invariant fails."""

    records = result["records"]
    assert isinstance(records, list)
    final = records[-1]
    first = final["firstNonlinear"]
    assert abs(first["linearCoefficient"] - 14.0) < 1.0e-5
    assert abs(first["quadraticCoefficient"] - 2.0) < 1.0e-5

    taylor = final["taylor"]
    stable_support_record = min(
        records,
        key=lambda record: abs(int(record["level"]) - 6),
    )
    assert stable_support_record["taylor"]["fullSupportCounts"] == [
        8,
        24,
        68,
        156,
        300,
        508,
    ]
    assert abs(taylor["relayNextScalar"] - taylor["directedFormula"]) < 1.0e-9
    assert taylor["fullNextLineDefect"] < 1.0e-7
    assert taylor["maximumRealityDefect"] < 1.0e-7
    assert taylor["maximumDivergenceDefect"] < 1.0e-5

    candidates = final["variation"]["unitCandidates"]
    two_cancelled = [
        candidate
        for candidate in candidates
        if candidate["cancelledDifferenceCount"] == 2
    ]
    one_cancelled = [
        candidate
        for candidate in candidates
        if candidate["cancelledDifferenceCount"] == 1
    ]
    assert len(two_cancelled) == 1
    assert abs(two_cancelled[0]["linearLeakage"] - 14.0) < 1.0e-5
    assert len(one_cancelled) == 2
    assert abs(one_cancelled[0]["linearLeakage"] - 10.25) < 1.0e-5

    assert result["sixLeafSolutions"] == [
        [1, 3, 2, 0],
        [2, 2, 1, 1],
        [3, 1, 0, 2],
    ]
    heat_profile = final["directedHeatProfile"]
    assert abs(heat_profile["maximumTime"] - 2.8351) < 2.0e-4
    assert abs(heat_profile["maximumAmplitude"] - 0.00375297) < 2.0e-7


def serializable(value: object) -> object:
    """Convert NumPy values recursively for JSON output."""

    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.generic):
        return value.item()
    if isinstance(value, dict):
        return {str(name): serializable(item) for name, item in value.items()}
    if isinstance(value, list):
        return [serializable(item) for item in value]
    return value


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--epsilon", type=float, default=0.2)
    parser.add_argument("--minimum-level", type=int, default=2)
    parser.add_argument("--maximum-level", type=int, default=8)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    result = audit(
        range(arguments.minimum_level, arguments.maximum_level + 1),
        arguments.epsilon,
    )
    if arguments.check:
        validate(result)
    print(json.dumps(serializable(result), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
