#!/usr/bin/env python3
import hashlib,json,os,re,sys
from fractions import Fraction as F
from pathlib import Path
R=Path(__file__).resolve().parents[1];S=R/'research/r075b_bulk_clock_outer_padding_gate.md';J=Path(os.getenv('R075B_JSON',R/'research/r075b_bulk_clock_outer_padding_gate_certificate.json'));O=Path(os.getenv('R075B_REPORT',R/'research/r075b_bulk_clock_outer_padding_gate_certificate_report.md'));M=os.getenv('R075B_MUTATION','');H='430feb9efc151e2b968dd1b7f785a19dc0e38416270ff8ed0275cfc6429b1a5a'
D={'research/r074h_collar_flux_two_regime_closure.md':'8c1d43f08d5a2c9299ae50ebdd10c8c184f064c6830f1d663524e03fa90d88f1','research/r074p_temporal_observable_triage.md':'a3cb872735b92b32ddfa7b96bc4184d70b0287ff2ce7d3da8cadbbcc494d0867','research/r074u_intrinsic_certified_residence.md':'e149243c81e6919c318ddcd4bc94c4830c74cfc586b776e29284f79a35336d99','research/r075a_spectral_persistence_payment_dichotomy.md':'f8117a7ff6380676d2ed05e749119579cc3f6972463834dcc6ad2a0b03026388'}
MU=('transport_sign','r_minus2','r_minus4','safe_weight_omega','outer_weight_quarter','rate_swap','full_clock','counterexample','nonzero_path','source_drift','dependency_drift','fraction','tag','reference','display','endpoint_open','accumulated_proved','collar_l3','neff_exponent','neff_threshold')
def sh(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 s=S.read_text();tags=re.findall(r'\\tag\{(B\.[^}]+)\}',s);refs=['B.'+x for x in re.findall(r'\(B\.([0-9]+[a-z]?)\)',s)];cg=F(8,3969);rho=F(9,10000);vals=[rho/4-F(5,24)*cg,cg/12-rho/6,rho/4-cg/12,rho/6-cg/12,3*(cg/12-rho/6)];want=[-F(92837,476280000),F(4279,238140000),F(27163,476280000),-F(4279,238140000),F(4279,79380000)]
 if M=='fraction':vals[0]+=F(1,10**9)
 req=["R075B_SAFE_COMPLETE_SUBCLOCK_PAID","R075B_OUTER_PADDING_ENDPOINT_PAID","R075B_OUTER_PADDING_DISSIPATION_OPEN","R075B_METHOD_FAILURE_NOT_COUNTEREXAMPLE","R075B_FULL_CLOCK_OPEN","Version-M mollified trajectory is identically","OUTER-COLLAR ENDPOINT: PAID","OUTER-COLLAR ACCUMULATED DISSIPATION: OPEN","N_{\\rm eff}:=","1\\le N_{\\rm eff}\\le N","CL^2R^3","W_{2R}\\ge\\gamma_k=\\omega","failure of this estimate**, not a counterexample","NOT\\ CLAY"]
 bad={'transport_sign':'WRONG_MINUS_TRANSPORT','r_minus2':'ERROR_ONLY_R_MINUS2','r_minus4':'ERROR_R_MINUS4','safe_weight_omega':'SAFE_USES_OMEGA','outer_weight_quarter':'OUTER_USES_QUARTER','rate_swap':'SAFE_OUTER_RATE_SWAP','full_clock':'FULL_CLOCK_PROVED','counterexample':'COUNTEREXAMPLE_PROVED','nonzero_path':'NONZERO_VERSION_M_PATH','endpoint_open':'OUTER_ENDPOINT_OPEN','accumulated_proved':'OUTER_ACCUMULATED_PROVED','collar_l3':'COLLAR_VOLUME_L3','neff_exponent':'NEFF_WRONG_EXPONENT','neff_threshold':'NEFF_WRONG_THRESHOLD'}
 if M in bad:req.append(bad[M])
 if M=='reference':refs.append('B.99')
 op=sum(x.strip()==r'\[' for x in s.splitlines())+(M=='display');cl=sum(x.strip()==r'\]' for x in s.splitlines())
 checks={'fractions':vals==want and vals[0]<0<vals[1] and vals[2]>0 and vals[3]<0<vals[4],'tags':len(tags)==47 and len(set(tags))==47 and M!='tag','refs':not(set(refs)-set(tags)),'display':op==cl,'sentinels':all(x in s for x in req),'source':sh(S)==('0'*64 if M=='source_drift' else H),'dependencies':all(sh(R/p)==h and f'`{p}` | `{h}`' in s for p,h in D.items()) and M!='dependency_drift','controls':not any(ord(c)<32 and c not in '\t\n\r' for c in s)}
 v='PASS' if all(checks.values()) else 'FAIL';data={'schema':'r075b-bulk-clock-outer-padding-v1','verdict':v,'mutation':M or None,'checks':checks,'assertions':len(checks),'tags':len(tags),'values':[str(x) for x in vals],'source_sha256':sh(S),'dependency_sha256':D,'negative_mutations':list(MU),'boundary':'FINITE EXACT ARITHMETIC/STRUCTURE ONLY; safe paid; outer method failure not counterexample; full clock open; NOT CLAY'}
 J.write_text(json.dumps(data,indent=2,sort_keys=True)+'\n');O.write_text(f'# R0.75B certificate report\n\n- Verdict: **{v}**\n- Assertions: {sum(checks.values())}/{len(checks)}\n- Tags: {len(tags)}\n- Mutations: {len(MU)}\n- Source SHA-256: `{sh(S)}`\n\nSafe subclock and outer endpoint paid; only outer accumulated dissipation and full clock remain open. FINITE EXACT ARITHMETIC/STRUCTURE ONLY. NOT CLAY.\n');print(json.dumps({'verdict':v,'checks':len(checks),'tags':len(tags),'mutation':M or None},sort_keys=True));return 0 if v=='PASS' else 1
if __name__=='__main__':sys.exit(main())
